version: '3'
services:
  scello_coupon_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      # - DATABASE_URL=postgres://postgres:secrect@postgres:5432/scelloo
      DB_USER: postgres
      DB_NAME: scelloo
      DB_PASSWORD: secrect
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      DB_NAME: scelloo
      POSTGRES_PASSWORD: secrect
    ports:
      - "5432:5432"
   